# yaml-language-server: $schema=../cache/schemas/tasks.json
$schema: "../cache/schemas/tasks.json"

inheritedBy:
  languages: [go]
  toolchains: [go]

fileGroups:
  sources:
    - glob: "**/*.go"
    - file: "go.mod"
    - file: "go.sum"

tasks:
  build:
    script: "go build -o bin/ ."
    type: build
    inputs:
      - "@globs(sources)"
    outputs:
      - glob: "bin/*"
  dev:
    script: "go run ."
    inputs:
      - "@globs(sources)"
  start:
    script: "go run ."
    deps:
      - build
    options:
      runInCI: false
  format:
    script: "go fmt ./..."
    type: test
    inputs:
      - "@globs(sources)"
  lint:
    script: "staticcheck ./..."
    deps:
      - "root:prepare-go"
    type: test
    inputs:
      - "@globs(sources)"
      - file: "staticcheck.conf"
        optional: true
  check:
    deps: ["lint", "format"]
  test:
    script: "go test ./..."
    type: test
    inputs:
      - "@globs(sources)"
  typecheck:
    script: "go vet ./..."
    type: build
    inputs:
      - "@globs(sources)"
