# yaml-language-server: $schema=../cache/schemas/tasks.json
$schema: "../cache/schemas/tasks.json"

inheritedBy:
  languages: [go]
  toolchains: [go]

tasks:
  build:
    script: "go build -o @out(0)"
    type: build
    inputs:
      - "@globs(sources)"
    outputs:
      - "bin/main"
  dev:
    script: "go run main.go"
    preset: server
    inputs:
      - "@globs(sources)"
  format:
    script: "go fmt ./..."
    type: test
    inputs:
      - "@globs(sources)"
  lint:
    script: "staticcheck"
    type: test
    inputs:
      - "@globs(sources)"
      - "staticcheck.conf"
  check:
    deps: ["lint", "format"]
  test:
    script: "go test ./..."
    type: test
    inputs:
      - "@globs(sources)"
  typecheck:
    script: "go vet"
    type: build
    inputs:
      - "@globs(sources)"
