# yaml-language-server: $schema=../cache/schemas/tasks.json
$schema: "../cache/schemas/tasks.json"

inheritedBy:
  languages: [javascript, typescript]
  toolchains: [node]

fileGroups:
  sources:
    - glob: "src/**/*"
  tests:
    - glob: "tests/**/*"
    - glob: "src/**/*.spec.ts"

tasks:
  typecheck:
    script: tsc --build --pretty --verbose
    type: build
    inputs:
      - "@globs(sources)"
      - "@globs(tests)"
      - "tsconfig.json"
      - "tsconfig.*.json"
      - "/tsconfig.options.json"
    outputs:
      - file: "tsconfig.tsbuildinfo"
        optional: true
      - glob: "lib/**/*"
        optional: true
  build:
    command: "tsdown"
    args: ["--sourcemap", "--target", "node26"]
    type: build
    inputs:
      - "@globs(sources)"
      - "package.json"
      - "tsconfig.json"
      - "tsconfig.*.json"
      - "/tsconfig.options.json"
    outputs:
      - glob: "dist/**/*"
  bundle:
    command: tsdown
    args: ["--sourcemap", "--minify", "--no-dts", "--target", "node26"]
    type: build
    inputs:
      - "@globs(sources)"
      - "package.json"
      - "tsconfig.json"
      - "tsconfig.*.json"
      - "/tsconfig.options.json"
    outputs:
      - "dist/**/*"
    options:
      mergeArgs: append
  dev:
    command: tsx
    args: ["src/index.ts"]
    deps:
      - typecheck
  start:
    command: node
    args: ["--enable-source-maps", "dist/index.mjs"]
    deps:
      - build
      - "^:build"
    env:
      NODE_ENV: "production"
    options:
      runInCI: false
  start-prod:
    command: node
    args: ["--enable-source-maps", "dist/index.mjs"]
    deps:
      - bundle
      - "^:build"
    env:
      NODE_ENV: "production"
    options:
      runInCI: false
  check:
    command: biome
    args: ["check", "--write"]
