# yaml-language-server: $schema=../cache/schemas/tasks.json
$schema: "../cache/schemas/tasks.json"

inheritedBy:
  tag: node_runtime

tasks:
  dev:
    command: tsx
    args: ["src/index.ts"]
    deps:
      - typecheck
  start:
    command: node
    args: ["--enable-source-maps", "dist/index.mjs"]
    deps:
      - build
      - "^:build"
    env:
      NODE_ENV: "production"
    options:
      runInCI: false
  start-prod:
    command: node
    args: ["--enable-source-maps", "dist/index.mjs"]
    deps:
      - bundle
      - "^:build"
    env:
      NODE_ENV: "production"
    options:
      runInCI: false
